-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.dictionary (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  word text NOT NULL UNIQUE,
  traditional text,
  hsk_level integer,
  frequency integer DEFAULT 0,
  translations jsonb NOT NULL DEFAULT '{}'::jsonb,
  source text DEFAULT 'user'::text,
  verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dictionary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.media_content (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  title text NOT NULL,
  description text,
  cover_image_url text,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['audio'::text, 'video'::text])),
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['upload'::text, 'youtube'::text, 'bilibili'::text, 'aigc'::text])),
  media_url text NOT NULL,
  external_id text,
  duration_seconds integer,
  hsk_level integer CHECK (hsk_level >= 1 AND hsk_level <= 6),
  difficulty_score double precision CHECK (difficulty_score >= 0::double precision AND difficulty_score <= 100::double precision),
  vocabulary_list ARRAY,
  topic_tag text,
  culture_tag text,
  indicator_cats ARRAY,
  transcript jsonb,
  processing_status text DEFAULT 'pending'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  processing_error text,
  processed_at timestamp with time zone,
  review_status text DEFAULT 'approved'::text CHECK (review_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  view_count integer DEFAULT 0,
  like_count integer DEFAULT 0,
  bookmark_count integer DEFAULT 0,
  uploaded_by uuid,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  word_timings jsonb,
  CONSTRAINT media_content_pkey PRIMARY KEY (id),
  CONSTRAINT media_content_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT media_content_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  nickname text,
  level smallint DEFAULT 1,
  streak_days smallint DEFAULT '0'::smallint,
  words integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  plan_duration_minutes integer DEFAULT 50,
  exp smallint DEFAULT '0'::smallint,
  sentences integer DEFAULT 0,
  grammars integer DEFAULT 0,
  plans smallint DEFAULT '0'::smallint,
  practices integer DEFAULT 0,
  characters smallint DEFAULT '0'::smallint,
  purpose USER-DEFINED,
  avatar text,
  deleted_at timestamp with time zone,
  email text,
  native_language text DEFAULT 'en'::text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.quizes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  indicator_id integer,
  activity_id integer,
  level smallint,
  topic_tag text,
  material text,
  material_type USER-DEFINED,
  stem jsonb,
  question text,
  options jsonb,
  explain text,
  culture_tag text,
  deleted_at timestamp with time zone,
  CONSTRAINT quizes_pkey PRIMARY KEY (id),
  CONSTRAINT quizes_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES research_core.activities(id),
  CONSTRAINT quizes_indicator_id_fkey FOREIGN KEY (indicator_id) REFERENCES research_core.indicators(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  revenue_cat_customer_id text UNIQUE,
  revenue_cat_entitlement_id text,
  status text NOT NULL DEFAULT 'free'::text,
  tier text,
  trial_start_at timestamp with time zone,
  trial_end_at timestamp with time zone,
  subscription_start_at timestamp with time zone,
  subscription_end_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  platform text,
  product_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_ability_history (
  id bigint NOT NULL DEFAULT nextval('user_ability_history_id_seq'::regclass),
  user_id uuid NOT NULL,
  indicator_id integer NOT NULL,
  score numeric NOT NULL CHECK (score >= 0::numeric AND score <= 1::numeric),
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT user_ability_history_pkey PRIMARY KEY (id),
  CONSTRAINT user_ability_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_ability_history_indicator_id_fkey FOREIGN KEY (indicator_id) REFERENCES research_core.indicators(id)
);
CREATE TABLE public.user_activity_instances (
  id bigint NOT NULL DEFAULT nextval('user_activity_instances_id_seq'::regclass),
  activity_id integer NOT NULL,
  indicator_id integer,
  materials jsonb,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  quiz jsonb,
  CONSTRAINT user_activity_instances_pkey PRIMARY KEY (id),
  CONSTRAINT user_activity_instances_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES research_core.activities(id),
  CONSTRAINT user_activity_instances_indicator_id_fkey FOREIGN KEY (indicator_id) REFERENCES research_core.indicators(id)
);
CREATE TABLE public.user_event_records (
  id bigint NOT NULL DEFAULT nextval('user_events_id_seq'::regclass),
  user_id uuid NOT NULL,
  category USER-DEFINED NOT NULL DEFAULT 'activity_record'::event_category,
  event_title text,
  event_detail jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT user_event_records_pkey PRIMARY KEY (id),
  CONSTRAINT user_event_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_materials (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  user_id uuid,
  level integer,
  chars jsonb,
  chars_review jsonb,
  words jsonb,
  words_review jsonb,
  syllables jsonb,
  grammars jsonb,
  sentences jsonb,
  dialogs jsonb,
  paragraphs jsonb,
  topic_title text,
  topic_tag text,
  culture_tag text,
  deleted_at timestamp with time zone,
  CONSTRAINT user_materials_pkey PRIMARY KEY (id),
  CONSTRAINT user_materials_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_media_progress (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  media_id bigint NOT NULL,
  playback_position double precision DEFAULT 0,
  completed boolean DEFAULT false,
  completion_rate double precision DEFAULT 0 CHECK (completion_rate >= 0::double precision AND completion_rate <= 1::double precision),
  play_count integer DEFAULT 0,
  total_watch_time double precision DEFAULT 0,
  last_played_at timestamp without time zone,
  shadowing_attempts integer DEFAULT 0,
  shadowing_scores ARRAY,
  average_shadowing_score double precision,
  is_bookmarked boolean DEFAULT false,
  bookmarked_at timestamp without time zone,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT user_media_progress_pkey PRIMARY KEY (id),
  CONSTRAINT user_media_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_media_progress_media_id_fkey FOREIGN KEY (media_id) REFERENCES public.media_content(id)
);
CREATE TABLE public.user_practices (
  id bigint NOT NULL DEFAULT nextval('user_activity_results_id_seq'::regclass),
  quizes ARRAY NOT NULL,
  score numeric CHECK (score >= 0::numeric AND score <= 1::numeric),
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  count integer DEFAULT 0,
  update_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  status smallint DEFAULT '0'::smallint,
  deleted_at timestamp with time zone,
  CONSTRAINT user_practices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_score_records (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  category text NOT NULL,
  item text,
  score numeric,
  user_id uuid NOT NULL,
  CONSTRAINT user_score_records_pkey PRIMARY KEY (id),
  CONSTRAINT user_score_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_vocabulary (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid NOT NULL,
  word text NOT NULL,
  pinyin text,
  definition text,
  example_sentence text,
  example_translation text,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['media'::text, 'practice'::text, 'manual'::text])),
  source_media_id bigint,
  source_practice_id bigint,
  source_context text,
  review_count integer DEFAULT 0,
  last_reviewed_at timestamp without time zone,
  next_review_at timestamp without time zone,
  mastery_level integer DEFAULT 0 CHECK (mastery_level >= 0 AND mastery_level <= 5),
  is_starred boolean DEFAULT false,
  notes text,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT user_vocabulary_pkey PRIMARY KEY (id),
  CONSTRAINT user_vocabulary_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_vocabulary_source_media_id_fkey FOREIGN KEY (source_media_id) REFERENCES public.media_content(id),
  CONSTRAINT user_vocabulary_source_practice_id_fkey FOREIGN KEY (source_practice_id) REFERENCES public.user_practices(id)
);
CREATE TABLE public.user_weekly_plans (
  id bigint NOT NULL DEFAULT nextval('user_weekly_plans_id_seq'::regclass),
  user_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date,
  target_indicators ARRAY,
  progress numeric DEFAULT 0,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  material_snapshot jsonb,
  target_material bigint,
  topic_title text,
  level integer,
  practices ARRAY,
  deleted_at timestamp with time zone,
  CONSTRAINT user_weekly_plans_pkey PRIMARY KEY (id),
  CONSTRAINT user_weekly_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_weekly_plans_target_material_fkey FOREIGN KEY (target_material) REFERENCES public.user_materials(id)
);